# Generated by Django 3.2.8 on 2022-04-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='genero',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
