# Generated by Django 3.2.8 on 2022-07-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='descripcion',
            field=models.TextField(default=1, verbose_name='Descripcion'),
            preserve_default=False,
        ),
    ]
