# Generated by Django 3.2.8 on 2022-07-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_category_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripcion'),
        ),
    ]
